version: '2.4'
services:
    api-manager:
      image: wso2/wso2am:4.0.0
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "9443"]
        interval: 10s
        start_period: 150s
        retries: 25
      ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
      - "9099:9099"
      - "9021:9021"
      volumes:
      - ./dockerfiles/conf/apim:/home/wso2carbon/wso2-config-volume
      depends_on:
        mi-runtime:
          condition: service_healthy
        si-runtime:
          condition: service_healthy
    mi-runtime:
      image: wso2/wso2mi:4.0.0
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "8290"]
        interval: 10s
        start_period: 30s
        retries: 20
      ports:
      - "8253:8253"
      - "8290:8290"
      - "9201:9201"
      depends_on:
        db:
          condition: service_healthy
      volumes:
        - ./dockerfiles/conf/mi:/home/wso2carbon/wso2-config-volume
        # - <SourceLocation>:/home/wso2carbon/sample
      environment:
        CATERING_SERVICE_EP : http://www.urldoesnotexist.com
      #   SMTP_HOST: <SMTP_Host>
      #   SMTP_PORT: <SMTP_Port>
      #   SMTP_USERNAME: <SMTP_Server_Username>
      #   SMTP_PASSWORD: <SMTP_Server_Password>
      #   EMAIL_TO: <To_Address>
      #   EMAIL_FROM: <From_Address>
    si-runtime:
      image: wso2/wso2si:4.0.0
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "9443"]
        interval: 10s
        start_period: 30s
        retries: 20
      volumes:
        - ./dockerfiles/conf/si:/home/wso2carbon/wso2-config-volume
      ports:
      - "8025:8025"
      - "9090:9090"
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
    backend-service:
      build: ./dockerfiles/backends/
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "8080"]
        interval: 10s
        start_period: 30s
        retries: 20
      ports:
      - "8082:8080"
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 1
    db:
      image: mysql:8.0.23
      ports:
        - 8083:3306
      command: --init-file /data/application/init.sql
      volumes:
        - ./dockerfiles/database/init.sql:/data/application/init.sql
      environment:
        MYSQL_ROOT_PASSWORD: pwd
        MYSQL_DATABASE: mysql
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
        interval: 10s
        retries: 20
        start_period: 10s
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
    scripts:
      build: ./dockerfiles/scripts
      mem_limit: 256m
      mem_reservation: 128M
      cpus: 1
      environment:
        APIM_HOST : api-manager
        RETRY_SEC : 5
        RE_RUN: 'false'
      depends_on:
        - "api-manager"
